env:
  browser: true
  es2021: true
extends:
  - xo
  # - xo-typescript
  - plugin:react/recommended
overrides:
  - extends:
      - xo-typescript/space
    files:
      - '*.ts'
      - '*.tsx'
    rules:
      indent:
        - error
        - 2
      semi:
        - error
        - never
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
settings:
  react:
    version: 'detect'
