services:
  server:
    restart: unless-stopped
    build: ./server
    init: true
    ports:
      - 8080:8080
    env_file:
      - server.env

  client:
    restart: unless-stopped
    build:
      context: ./client
      target: development
    init: true
    volumes:
      - ./client/src:/app/src
    ports:
      - 8081:8081
    environment:
      - GATSBY_KCHAT_SERVER_URL=ws://localhost:8080
