services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      target: production
    init: true
    environment:
      - "VIRTUAL_HOST=server.kchat.local"
    networks:
      - proxy-tier

  client:
    restart: unless-stopped
    build:
      context: ./client
      target: production
      args:
        - "GATSBY_KCHAT_SERVER_URL=wss://server.kchat.local:8443"
    environment:
      - "VIRTUAL_HOST=kchat.local"
      # - "GATSBY_KCHAT_SERVER_URL=wss://server.kchat.local:8443"
    networks:
      - proxy-tier

networks:
  proxy-tier:
    name: common-proxy
    external: true
