services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      target: production
    init: true
    networks:
      - proxy-tier
    environment:
      - "VIRTUAL_HOST=kchat-server.localhost"

  client:
    restart: unless-stopped
    build:
      context: ./client
      target: production
    environment:
      - "VIRTUAL_HOST=kchat.localhost"
      - "GATSBY_KCHAT_SERVER_URL=wss://kchat-server.localhost:8443"
    networks:
      - proxy-tier

networks:
  internal:
  proxy-tier:
    name: common-proxy
    external: true
