services:
  server:
    restart: unless-stopped
    image: ghcr.io/andriy-f/webchat-server
    init: true
    environment:
      - "VIRTUAL_HOST=server.chat.ggrsoft.info"
      - "LETSENCRYPT_HOST=server.chat.ggrsoft.info"
      - "LETSENCRYPT_EMAIL=forspam.smith+lenc@gmail.com"

  client:
    restart: unless-stopped
    image: ghcr.io/andriy-f/webchat-client

networks:
  internal:
  proxy-tier:
    name: common-proxy
    external: true
