services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      target: development
    init: true
    ports:
      - 8080:8080
    env_file:
      - server.env

  client:
    restart: unless-stopped
    build:
      context: ./client
      target: development
    init: true
    volumes:
      - ./client/src:/app/src
    ports:
      - 8081:8081
    env_file:
      - client.env
